# NumPy Tutorial

*lets practice numpy

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.arange(1,10)
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [7]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [8]:
#Creation of identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
#uniform distribution
np.random.rand(3,2)

array([[0.99293118, 0.7060993 ],
       [0.57136965, 0.38148705],
       [0.77535629, 0.24058234]])

In [27]:
#standard normally distribution
#ie mean = 0 and standard deviation = 1
np.random.randn(3,2)

array([[ 0.45423448, -0.03335589],
       [-0.0415827 , -0.30796913],
       [-0.37012255,  1.08759176]])

In [33]:
np.random.randint(5,7,2)

array([6, 5])

In [38]:
array_30=np.arange(1,31,1)
matrix_5_6 = array_30.reshape(5,6)
matrix_5_6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [40]:
array_30.max()
array_30.argmax()

29

In [43]:
array_30.shape

(30,)

In [44]:
array_30


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
array_30.dtype


dtype('int32')

In [49]:
#Transpose
matrix = array_30.reshape(5,6)
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [50]:
matrix.T

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])